### ISSUE TITLE
Alignment of timestamp and controls

### ISSUE THREAD

**Issue by squadette** [church-of-unlikely/mokum-bugs#2]
Timestamp and controls should be aligned in the same way as likes and comments.  If the post is private, lock icon should go before the timestamp.

<img width="826" alt="screen shot 2016-10-22 at 03 20 30" src="https://cloud.githubusercontent.com/assets/3052/19615964/81e48036-9808-11e6-8f3d-4c1d9ca14403.png">

**Comment by ayoshi** [comment]
Fixed
